run:
  timeout: 2m
  tests: false

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  lll:
    line-length: 160
    tab-width: 8
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - dupl
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - prealloc
    - unparam
    - unconvert
    - whitespace

  max-same-issues: 0

issues:
    exclude-rules:
      - path: cmd/build-config/main.go
        linters:
          - gochecknoglobals
