name: build linux/amd64

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
#      - name: Test
#        run: go test -v ./...
      - name: Build
        run: go build -o ./get5 ./cmd/build-config/main.go
      - name: publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./get5"
          allowUpdates: true
          name: "latest"
          token: ${{ secrets.GET5CLI_RELEASE_TOKEN }}
