name: linux/amd64

on:
  schedule:
    - cron: '0 0 1 */2 *' # Every other month

  push:
    branches: [ master ]

  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -ldflags="-X main.GitCommitHash=$(git rev-parse HEAD)" -o ./get5 ./cmd/build-config/main.go
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: get5-cli
          path: ./get5-cli
