name: build linux/amd64

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Build
        run: go build -o get5 ./cmd/build-config/main.go
#      - name: Test
#        run: go test -v ./...
